-- Supabase Setup Script for DHL Knowledge Base

-- 1. Create the 'articles' table
CREATE TABLE IF NOT EXISTS articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  tags TEXT,
  status TEXT DEFAULT 'Draft',
  creator_email TEXT
);

-- 2. Enable Row Level Security (RLS)
-- Note: This is a basic setup. For production, you should define more restrictive policies.
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow public access (Read and Write)
-- This allows the demo application to work without complex Auth setup.
CREATE POLICY "Enable all access for all users" ON articles 
FOR ALL 
USING (true) 
WITH CHECK (true);
